# Generated by Django 5.2.4 on 2026-05-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratelimit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="requestlog",
            name="ratelimit_r_client__94182f_idx",
        ),
        migrations.AddField(
            model_name="requestlog",
            name="counter",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
