# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratelimit", "0002_remove_requestlog_ratelimit_r_client__94182f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="client_ip",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
